# Change these first
owner: tenchi-security # Your GitHub organization or username, where this repository lives
repo: zanshin_status # The name of this repository

sites:
  - name: Zanshin Portal
    icon: https://zanshin.tenchisecurity.com/assets/images/logo/notext_color.svg
    url: https://zanshin.tenchisecurity.com
    assignees:
      - lucas-subli
    headers:
      - "User-Agent: status.zanshin.tenchisecurity.com"
  - name: Zanshin API health check
    icon: https://zanshin.tenchisecurity.com/assets/images/logo/notext_color.svg
    url: https://api.zanshin.tenchisecurity.com/ping
    assignees:
      - rfranco
    headers:
      - "User-Agent: status.zanshin.tenchisecurity.com"
  - name: Zanshin API user check
    icon: https://zanshin.tenchisecurity.com/assets/images/logo/notext_color.svg
    url: https://api.zanshin.tenchisecurity.com/me
    assignees:
      - rfranco
    headers:
      - "Authorization: Bearer $ZANSHIN_API_KEY"
      - "Accept: application/json"
      - "Accept-Encoding: gzip, deflate"
      - "User-Agent: status.zanshin.tenchisecurity.com"
  - name: Zanshin API alert check
    icon: https://zanshin.tenchisecurity.com/assets/images/logo/notext_color.svg
    url: https://api.zanshin.tenchisecurity.com/a72f4225-43e9-4922-b6b7-8b0620bdb1c0/alerts
    method: POST
    assignees:
      - rfranco
    headers:
      - "Content-Type: application/json"
      - "Authorization: Bearer $ZANSHIN_API_KEY"
      - "Accept: application/json"
      - "Accept-Encoding: gzip, deflate"
      - "User-Agent: status.zanshin.tenchisecurity.com"
    body: '{}'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zanshin.tenchisecurity.com
  # baseUrl: /your-repo-name
  logoUrl: https://zanshin.tenchisecurity.com/assets/images/logo/name_border.svg
  favicon: https://zanshin.tenchisecurity.com/favicon.ico
  name: Zanshin Status Page
  introTitle: "Continuous, comprehensive and actionable assessments of third-party cloud security."
  introMessage: If you need assistance, please [e-mail our support team](mailto:support@tenchisecurity.com) or log into our [support portal](https://support.tenchisecurity.com).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: ocean

commitMessages:
  commitAuthorName: "Tenchi Security Uptime Bot"
  commitAuthorEmail: "support@tenchisecurity.com"

assignees:
  - asieira
  - edpin
  - lfpontes-tenchi

user-agent: tenchi-security status page

i18n:
  footer: Powered by [Tenchi Security](https://www.tenchisecurity.com)

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
